# -*- coding: utf-8 -*-
"""stock price .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GC3Jy9msDsNfp8yy2hq-HabXVr0l_hV
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt


ticker = "AAPL"

print(f"Downloading {ticker} data...")
data = yf.download(ticker, period="6mo", interval="1d")


# 3️ Calculate Moving Averages

data["MA20"] = data["Close"].rolling(window=20).mean()
data["MA50"] = data["Close"].rolling(window=50).mean()


# 4️ Plot the data

plt.figure(figsize=(12, 6))
plt.plot(data["Close"], label="Close Price", color="blue", linewidth=1.5)
plt.plot(data["MA20"], label="20-Day MA", color="green", linestyle="--")
plt.plot(data["MA50"], label="50-Day MA", color="red", linestyle="--")

plt.title(f"{ticker} Stock Price with Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price (USD)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# 5️Save data to CSV

csv_file = f"{ticker}_stock_data.csv"
data.to_csv(csv_file)
print(f"✅ Data saved successfully to '{csv_file}'")

